USE ROLE ACCOUNTADMIN;
GRANT OWNERSHIP ON DATABASE PRD_ALV TO ROLE ACCOUNTADMIN;

-- Create or replace the warehouse
CREATE OR REPLACE WAREHOUSE PRD_ALV_WAREHOUSE
  WAREHOUSE_SIZE = 'X-SMALL'
  WAREHOUSE_TYPE = 'STANDARD'
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE
  COMMENT = 'Warehouse for ALV production environment';

-- Create or replace the database
CREATE OR REPLACE DATABASE PRD_ALV
  COMMENT = 'ALV production database';

USE DATABASE PRD_ALV;

-- Create or replace the schema for the QUERY_LINKEDIN component
CREATE OR REPLACE SCHEMA QUERY_LINKEDIN
  COMMENT = 'Schema for the QUERY_LINKEDIN component';

use schema QUERY_LINKEDIN;


-- Create or replace the role
CREATE OR REPLACE ROLE ALV_PROD_ROLE
  COMMENT = 'Role for accessing ALV production environment';

use DATABASE PRD_ALV;
GRANT OWNERSHIP ON SCHEMA QUERY_LINKEDIN TO ROLE ALV_PROD_ROLE;

GRANT OWNERSHIP ON DATABASE PRD_ALV TO ROLE ALV_PROD_ROLE;

GRANT USAGE ON WAREHOUSE PRD_ALV_WAREHOUSE TO ROLE ALV_PROD_ROLE;

GRANT ROLE ALV_PROD_ROLE TO ROLE SYSADMIN;

